### ISSUE TITLE
Can't delete WIP songs

### ISSUE THREAD

**Issue by Fatalution** [kinsi55/BeatSaber_BetterSongList#1]
Well, basically title. The delete button is just greyed out - not pushable (similar to how the play button is for WIPs)

**Comment by kinsi55** [comment]
Have you checked the settings :P

**Comment by Fatalution** [comment]
Ohkay, found it.
I would advise moving settings to settings -> Mod Settings tho (or at least duplicating them there if that's an option). Currently it took me a while to find the settings button :D
