### ISSUE TITLE
Request:  multiple filter

### ISSUE THREAD

**Issue by catharsis71** [kinsi55/BeatSaber_BetterSongList#15]
It would be nice to be able to select something like "only unplayed" and "only unranked" simultaneously

I know that's the sort of thing that BetterSongSearch can do but it's much more cumbersome to use and doesn't have an "only unranked" option (which I just filed an issue for)

I tried combining BetterSongList's filtering with the game's native filtering, but it's not ideal, namely because using the game's native "Only Unplayed" filter results in some wonky behavior

**Comment by kinsi55** [comment]
Allowing for this would hugely complicate both the code as well as the UI for something that is meant to be simple and "enough for 99% of the use cases" so I wound indeed refer you to better song search for more flexibility

> and doesn't have an "only unranked" option (which I just filed an issue for)

Filtering unranked is possible (responded)
