### ISSUE TITLE
"Error getting data." on Windows 11

### ISSUE THREAD

**Issue by tablekat** [kinsi55/BeatSaber_BetterSongList#18]
Not sure if this is just a Windows 11 thing or some sort of cruel divine punishment on just me, but I get this issue of the game showing "Error getting data." for a while when going to my songs list. After some random amount of time, the list will end up loading. I also am unable to load certain songs and will just get a spinner continually if I select them in the list. This only occurs when I have BetterSongList installed, and if I remove it I get the vanilla song list without the error.

Exciting screenshots:
https://i.imgur.com/JDgva1U.png
https://i.imgur.com/KZjGJjz.png

I've reinstalled a few times, and have had issues with other mods. For example, the game would just fully not start on this computer at all until I upgraded to the latest BSIPA version from github (4.2.1). Some other mods seem to also fail to load at all, like SongBrowser if I install that.

**Comment by kinsi55** [comment]
Seems like your SongCore just doesn't work. Can you reproduce the issues, close the game and attach the `_latest.log` from the logs folder?

**Comment by tablekat** [comment]
I'm able to access custom songs so I assumed SongCore was doin okay. Here's the log,

[_latest.log](https://github.com/kinsi55/BeatSaber_BetterSongList/files/8431797/_latest.log)

**Comment by kinsi55** [comment]
Custom songs are a basegame feature - SongCore just makes them much less of a pain.

Your IPA version (4.2.1) is too new for your game version. You have a couple choices here:

- Reinstall / go to 1.21 (Probably easiest)
- Try to manually downgrade to [IPA 4.2.0](https://github.com/bsmg/BeatSaber-IPA-Reloaded/releases/tag/4.2.0) and hope your game does not explode in the process of doing so

Furthermore, you will probably want to update your [SongDetails](https://github.com/kinsi55/BeatSaber_SongDetails/releases/tag/v1.2.1)

As to if doing that might cause something to explode, I cannot exactly tell you right now. I dont think so but it might.
