### ISSUE TITLE
Display Reaction Time

### ISSUE THREAD

**Issue by BlqzingIce** [kinsi55/BeatSaber_BetterSongList#19]
An option to display a map's set reaction time instead of offset/jump distance in the level params.
Easily calculatable from jump distance: `reactiontime = jumpdistance / (2 * njs) * 1000;` (in ms)
Maybe change the existing jump distance setting to a dropdown menu to accommodate the extra option?

**Comment by kinsi55** [comment]
I considered that before but I feel like the only real purpose of the default offset is for mappers / giving mapping feedback tbh since most people nowadays override the offset anyways. I'll consider it for a future update tho

**Comment by BlqzingIce** [comment]
Personally, I don't really get much from the offset (to be fair I am not a mapper), and I get some info from jump distance, but reaction time is just so much more intuitive to understand. I appreciate you considering it!

**Comment by kinsi55** [comment]
Yeah but like knowing the maps default RT doesnt really give you much if you are overriding it anyways

**Comment by BlqzingIce** [comment]
I still think it would be useful information to have built into the song select menu, but that's true, for people who change everything anyways it's doesn't really matter.

**Comment by kinsi55** [comment]
Closing this as that info field isnt offset anymore anways but map age now
