### ISSUE TITLE
Crouch Wall Icon No Longer Shows - BS1.22.1

### ISSUE THREAD

**Issue by tophattwaffle** [kinsi55/BeatSaber_BetterSongList#21]
On BS 1.22.1 with Better Song List 0.3.0 the crouch wall icon does not show next to the wall count.

![image](https://user-images.githubusercontent.com/6774125/173443926-1fa6f149-710a-4a4c-8067-c20033f81d4c.png)

Song with crouch walls: https://beatsaver.com/maps/17726

**Comment by kinsi55** [comment]
Good catch 👍
