### ISSUE TITLE
Can plugin sort by each DifficultyBeatmap?

### ISSUE THREAD

**Issue by nanikit** [kinsi55/BeatSaber_BetterSongList#23]
I'm implementing accuracy sorter, but each difficulty has different accuracy so I want to highlight the difficulty (and the characteristic) for showing which difficulty is selected as sorted accuracy.

At a glance BetterSongList doesn't care this so maybe I'll manipulate / hook base game object directly. But at least I have to know whether my accuracy sorter is selected or deselected so I can toggle highlighting at proper time.

Do you have any idea? I can't sure whether there is a way for knowing selection changes already.

**Comment by kinsi55** [comment]
You should implement it the same way as, for example, the "Ranked Stars" sorter - When sorting Ascending, sort by the lowest value of all difficulties, when sorting Descending by the highest value of all difficulties.

As for knowing when your sort / filter is selected, no that currently is not a thing. I could add it but Sorters / Filters really shouldnt be modifying the UI imo.

**Comment by nanikit** [comment]
> You should implement it the same way as

I can't agree with this yet. One of my objectives is to find easy song for better acc or rest. I won't be able to find easy difficulty of song containing harder difficulty. It is not a thing for challenger, but it's a thing for me.

> Sorters / Filters really shouldnt be modifying the UI imo.

That sounds like what I'm making isn't sorter. Then if I still want to do this, then should I fork your plugin?

**Comment by kinsi55** [comment]
What you are building should be a seperate plugin since you plan to use more complex logic.

It seems like you are trying to accomplish similar goals as [SmartSongSuggest](https://github.com/HypersonicSharkz/SmartSongSuggest/wiki) / PP booster. Sorters / Filters in Better Song List should be completely objective, 1:1 based off the numbers of the map

**Comment by nanikit** [comment]
I just tried the mod you suggested (SmartSongSuggest, another one seems to be not maintained). I understand your words as you defined sorter as you mentioned, and my behavior will not be supported.

I want to use the base game UI so I want to reuse many parts of this plugin (BetterSongList), may I fork your plugin or do a harmony thing?

**Comment by kinsi55** [comment]
Obviously I cannot prevent you from making a fork - I can just give you my advice and say what you build should be a standalone plugin which then for example generates a playlist like SmartSongSuggest. You will sooner than later run into limitations because you are trying to make the basegame UI do something its not meant to do.

**Comment by nanikit** [comment]
I think I finally understand you words. So because I want to reuse basegame UI, the behavior I wanted will make fragile part.

Then suggested alternative is making new UI by using BSML or else. But I'm not experienced with this, current shortest path is just using this plugin. Maybe this will break in the future, I can think about it later.

**Comment by kinsi55** [comment]
Essentially yeah - But also having a custom UI allows for a much better User experience because you can display information much more clearly.

BSML is not super hard, if you want a simple example to play around with check out [Tweaks](https://github.com/kinsi55/BeatSaber_Tweaks55) :)

**Comment by nanikit** [comment]
I think the best user experience is using the current UI, just this abusing limitation is the only obstacle and reasonable not to select it.

There are reasons. There is no need to learn new things, no cost to mode change, and it gives integrated feeling.

So I will try this first, and maybe I can learn BSML later.
