### ISSUE TITLE
"Error getting data" when clicking on solo (1.31)

### ISSUE THREAD

**Issue by LargoSharko** [kinsi55/BeatSaber_BetterSongList#28]
Hey, been a while since i played beatsaber so i just updated all my mods with mod assistant and noticed this wasn't in it. Finally found this and gave it an install and my whole game locks up when i click on solo with this installed in the plugins folder. Would appreciate some help, here's the log.

[_latest.log](https://github.com/kinsi55/BeatSaber_BetterSongList/files/12207977/_latest.log)

**Comment by kinsi55** [comment]
Most mods, including most of mine, are not yet updated for the latest version (Hence them not being in ModAssistant). You'll need to downgrade. 1.29.1 is probably your best bet for now

**Comment by LargoSharko** [comment]
Perfect, got this working now. Thank you so much, didn't realize that it had updated recently/so much was out of date

**Comment by kinsi55** [comment]
You can leave the issue open, its an issue afterall :P

**Comment by aaronjamt** [comment]
Any way I can help with this?

**Comment by kinsi55** [comment]
Most of mine mods that broke did so because of the very same reason which is rather easy to fix. I'll try to get onto it soon

**Comment by kinsi55** [comment]
Fixed in latest update

**Comment by aaronjamt** [comment]
> Most of my mods that broke did so because of the very same reason which is rather easy to fix. I'll try to get onto it soon

Can you elaborate on what exactly you did to fix it? I'd like to try to help fix other mods, so if I can take those steps and use them elsewhere that'd be really cool

**Comment by kinsi55** [comment]
@aaronjamt Obviously its possible that more stuff broke in other mods, but for the most part its them having removed the SharedCoroutineStarter class for which I've created a simple replacement: https://github.com/kinsi55/BeatSaber_BetterSongList/blob/master/Util/SharedCoroutineStarter.cs

**Comment by aaronjamt** [comment]
> @aaronjamt Obviously its possible that more stuff broke in other mods, but for the most part its them having removed the SharedCoroutineStarter class for which I've created a simple replacement: https://github.com/kinsi55/BeatSaber_BetterSongList/blob/master/Util/SharedCoroutineStarter.cs

Awesome, thanks for the information and for updating this mod!
