### ISSUE TITLE
Letter Captialization is not ignored for Alphabet scrollbar

### ISSUE THREAD

**Issue by Naephilim** [kinsi55/BeatSaber_BetterSongList#6]
I have both SongCore and this mod on and everytime I access solo mode, I get this notification. 
![BetterSongList Error](https://user-images.githubusercontent.com/76447675/135732054-59279295-6ed0-44bc-8e03-a1505e435464.png)

**Comment by kinsi55** [comment]
This isnt about SongCore but about Song**Data**Core, which it advises you to remove.

**Comment by Naephilim** [comment]
This did remove the notification. Slight misread. I apologise.

I also thought this error was also causing the double letters on the "song name" sorting. Is this intentional? Because it reads both capital and lower case of the same letter on the list.
![Double letters](https://user-images.githubusercontent.com/76447675/135732321-40fe153b-3359-4782-88b9-269772e471df.png)

**Comment by kinsi55** [comment]
That is in fact not intended, I'll fix that.
