### ISSUE TITLE
Only showing a few songs in custom songs list

### ISSUE THREAD

**Issue by Jaitie018** [kinsi55/BeatSaber_BetterSongList#7]
Every time i launch beatsaber and go to the custom songs tab only a few songs are listed not even the hearted songs are showing up

**Comment by kinsi55** [comment]
Are you sure you dont have some Filter active at the bottom?

**Comment by Jaitie018** [comment]
im a fucking retard

**Comment by kinsi55** [comment]
It happens to the best of us
