### ISSUE TITLE
How about adding last played date sorter?

### ISSUE THREAD

**Issue by nanikit** [kinsi55/BeatSaber_BetterSongList#9]
I miss this feature of osu game's one. Just suggestion, feel free to close if you mind.

**Comment by kinsi55** [comment]
I think it could be useful. I'll look into it at some point.

**Comment by nanikit** [comment]
I started working on it. If you have something to consider, please share to me.

**Comment by kinsi55** [comment]
I think this is something that I'd like to be an optional / third party sorter. If you are not aware, I will be adding and API that allows others to add sorts and filters to BSL so everyone can add whatever they want, even if I disagree with it.

**Comment by nanikit** [comment]
Then I will try to make it as a separate plugin. All left is maybe plugin API, it looks like it could be a PR. If API is delayed then I'll try it.

**Comment by kinsi55** [comment]
My main Issue with the API is that I have not yet figured out how to built it *neatly* because I want other plugins to have the ability to also disable their sorts / filters, depending on what Playlist / song etc you are currently in. I think I might have to do a minor refactor of how sorts / filters are implemented.

**Comment by nanikit** [comment]
I used the following for the development so far. What do you think about it?

```csharp
namespace BetterSongList.Api {
	public interface ISortFilter {
		/// <summary>
		/// Sorter / filter name, appears on dropdown.
		/// </summary>
		string Name { get; }

		/// <summary>
		/// Whether show in dropdown or not
		/// </summary>
		ObservableVariable<bool> IsVisible { get; }

		/// <summary>
		/// Notify beatmap level changes.
		/// </summary>
		/// <param name="newLevels">All levels before sort or filter.</param>
		/// <param name="isSelected">Is the result levels should be changed because it is selected?</param>
		/// <returns>Processing task.</returns>
		Task NotifyChange(IEnumerable<IPreviewBeatmapLevel>? newLevels, bool isSelected = false, CancellationToken? token = null);

		/// <summary>
		/// Sort / filter result.
		/// </summary>
		ObservableVariable<IEnumerable<IPreviewBeatmapLevel>> ResultLevels { get; }
	}

	public interface ILegendProvider {
		ObservableVariable<IEnumerable<(string Label, int Index)>> Legend { get; }
	}
}
```

**Comment by kinsi55** [comment]
What is the point of using `ObservableVariable` here? Havent seen anyone actually use that before.

What I had in mind was having a callback for external sorters / filters which passes them what it is thats currently selected (To streamline the process so thirdparty sorts / filters dont have to get this information themselves) which should be synchronous (return) so that the dropdowns update instantly on switch.

**Comment by kinsi55** [comment]
I'll use FS as a shorthand for sorts / filters here because its kinda redundant mentioning it all the time

> I used that for plugin's arbitrary value update. For example pp sorter can request pp information to scoresaber, and update the result later and it can be multiple times *& following section*

I dont like that idea, that would increase complexity / edge cases a lot and might degrade performance (Say you are scrolling through the list or seraching for a song and the sorter decides to update, possibly resorting the list and / or resetting the search), so I would like to keep the current flow of having a prepare method which is called when the FS is used and forcing the actual data manipulation to be synchronous

**Comment by nanikit** [comment]
If we don't await `NotifyChange`, actual data manipulation can be synchronous.

More controversial point is maybe whether plugin can be able to update anytime or not.

**Comment by nanikit** [comment]
If we don't await `NotifyChange`, actual data manipulation can be synchronous.

More controversial point is maybe whether plugin can be able to update anytime or not. I initially thought when player finished playing, then I can update the list except the last played song. I didn't intend modifying the list very frequently. But if you think you should control update timing, then the `ISortFilter` should be changed.

**Comment by nanikit** [comment]
```csharp
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;

namespace BetterSongList.Api {
	public interface ISortFilter {
		/// <summary>
		/// Sorter / filter name, appears on dropdown.
		/// </summary>
		string Name { get; }

		/// <summary>
		/// Notify beatmap level changes.
		/// </summary>
		/// <param name="newLevels">All levels before sort or filter.</param>
		/// <param name="isSelected">Is the result levels should be changed because it is selected?</param>
		void NotifyChange(IEnumerable<IPreviewBeatmapLevel>? newLevels, bool isSelected = false, CancellationToken? token = null);

		/// <summary>
		/// null means sorter / filter is not usable.
		/// </summary>
		event Action<ISortFilterResult?> OnResultChanged;
	}

	public interface ISortFilterResult {
		/// <summary>
		/// Sort / filter result.
		/// </summary>
		IEnumerable<IPreviewBeatmapLevel> ResultLevels { get; }

		IEnumerable<(string Label, int Index)>? Legend { get; }
	}
}
```
Reflected the discussions so far. Still request for comments.

**Comment by kinsi55** [comment]
Just so I dont make any wrong assumptions, Is this intended to universally replace my current structure of FS or is this meant to only be used by plugin FS?

**Comment by nanikit** [comment]
I don't care. Currently I used universally replacement way crude implementation just for test, but if you provide API I'll use that.

**Comment by kinsi55** [comment]
I think what I would do:

- Make the FilterMethods and SortMethods classes public, as well as all of the Interfaces of course thus allowing / suggesting plugin FS to use those if they dont need more complex logic
- Where applicable, seal the existing models so people dont try to inherit from those
- Add a new Interface *`UndecidedName`* with the Callback method, called whenever the "Context" switches, so when a different tab or playlist is selected (*Undecided Signature*) which returns a bool that dictates if the FS should be visible, or not. This would give a mod like Hitbloq the chance to allow sorting by that specific Hitbloq pool's difficulty rating, if the user is in a Hitbloq playlist
- Add a `Register<T>` method to the `FilterMethods` and `SortMethods` classes where you pass a name (Displayed in the Dropdown) and the FS instance - T must be *`UndecidedName`* as well as `ISorter` / `IFilter` respectively. Having a Unregister might also make sense for Disableable plugins (Modlist will be a thing eventually)

I would then have the plugin FS always be at the top of the dropdowns so they do not mess with muscle memory of builtin options depending on if they are hidden or not and additionally display a symbol i front of them, indicating they are a plugin FS (Maybe 🔌)

This should keep things very consistent between first- and thirdparty FS with just minor differences

**Comment by nanikit** [comment]
I'll wait for your work.

**Comment by kinsi55** [comment]
I will try to come up with an implementation later

**Comment by kinsi55** [comment]
Progress

![devenv_2022-03-03_18-03-06](https://user-images.githubusercontent.com/8348306/156614161-2377c275-682b-4cd8-a3b1-7489abfd559b.png)

![Beat_Saber_2022-03-03_18-01-59](https://user-images.githubusercontent.com/8348306/156614046-56ef6e80-982b-47a0-a22a-0d5beeea572a.png)

**Comment by nanikit** [comment]
I have several questions.

- Could I change the sort result at any time?
- `levelCategory` and `playlist` are necessary information for all plugin? How about making it as static property?

I uploaded my testing plugin on [here](https://github.com/nanikit/BetterSongList.LastPlayedSort) just for reference. I didn't implement all features.

I made BetterSongList support asynchronous (though my plugin doesn't use it).

**Comment by kinsi55** [comment]
I've pushed my proposed implementation now. Keep in mind the ContextSwitch callback is not implemented yet.

**Comment by nanikit** [comment]
OK it works.
![image](https://user-images.githubusercontent.com/45276129/156790527-05ba4a1c-7b96-4187-8336-477d21f13914.png)

**Comment by nanikit** [comment]
FYI BetterSongList does not remember last selected custom sorter. Could you add this feature?

**Comment by kinsi55** [comment]
Yeah I'll fix that, this was just a basic implementation test

**Comment by kinsi55** [comment]
I just pushed the changes necessary for 1.20, you can add the preprocessor flag `PRE_1_20` to compile for 1.19. I think I fixed it not saving the last option if its a custom one and also implemented the ContextChange method. If you could give this a try and see if it works fine that'd be great

**Comment by kinsi55** [comment]
Cool. If you find any issues with it let me know, else this will be what I release once 1.20 mods roll out

**Comment by nanikit** [comment]
I close this because plugin feature is shipped. I may file a separate issue if there is problem.
